### ISSUE TITLE
DVN vs. Dataverse vs. Harvard Dataverse

### ISSUE THREAD

**Issue by pdurbin** [andybega/icews#43]
Hi! I spotted this project on Twitter at https://twitter.com/andybeega/status/1103226111855607809

I noticed that you're using "DVN" in your README (e.g. "the current version on DVN") but in some contexts, "Harvard Dataverse" would be preferred. Let me try to summarize a few terms:

- **DVN**: A somewhat awkward acronym for "Dataverse Network", which was the old name (in the 3.x and earlier days) for the software that is now called "Dataverse".
- **Dataverse**: The current name for the software formerly known as "DVN".
- **Harvard Dataverse**: One of 39 installations of Dataverse and home of ICEWS event data. Other installations of Dataverse include UNC Dataverse, Scholars Portal Dataverse, etc.

I'd be happy to make a pull request if you'd like. Please let me know. Thanks! Great project!

Also, if you're interested in helping with the "dataverse" R package, please leave a comment at https://github.com/IQSS/dataverse-client-r/issues/21 😄

**Comment by andybega** [comment]
Hi, thanks for the clarification! I tried to replace some of the references in the README and documentation, but haven't checked very thoroughly whether I caught all. 

Let me know or make a pull request if anything else should be changed.

**Comment by pdurbin** [comment]
@andybega overall, that  commit looks fantastic but it's making me realize that I could define an additional term:

- **Integrated Crisis Early Warning System (ICEWS) Dataverse**: A sub-dataverse of Harvard Dataverse that contains ICEWS event data.

Let me play with your README a bit and decide if I think it's worth making a pull request. Thanks for being open to pull requests and for the changes so far!

**Comment by pdurbin** [comment]
I took a closer look and I think the README is fine. My only suggestion is to replace "repos" with "datasets" but that's off topic for this issue. Thanks! Closing.
